### ISSUE TITLE
Is this Python 3 issue?

### ISSUE THREAD

**Issue by anetasie** [JohannesBuchner/BXA#6]
I just installed bxa (pip install on Mac OS High Sierra), but I get an error when I'm trying to import bxa.sherpa to my ipython:

```
$ ipython
Python 3.7.2 (default, Dec 29 2018, 00:00:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from __future__ import print_function                                                                           

In [2]: import bxa.sherpa as bxa                                                                                        
Traceback (most recent call last):

  File "/Users/aneta/anaconda3/envs/test_py3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-2-19cf673f1dd0>", line 1, in <module>
    import bxa.sherpa as bxa

  File "/Users/aneta/anaconda3/envs/test_py3.7/lib/python3.7/site-packages/bxa/sherpa/__init__.py", line 63
    print 'Exception in log_likelihood function: ', e
                                                 ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Exception in log_likelihood function: ', e)?

```

**Comment by anetasie** [comment]
Yes, I just noticed. I'll try to use the git version.

**Comment by JohannesBuchner** [comment]
I just made a new release -- If you still have a problem with the latest version, please reopen this issue.
